# Generated by Django 4.1 on 2025-04-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(to="octofit_app.user"),
        ),
    ]
